startdate: "20230101T000000"
enddate: "20230131T235959"
workdir: "/n/holyscratch01/jacob_lab/nbalasus/IMI_BCs"
gccache: "/n/holylfs05/LABS/jacob_lab/lestrada/IMI/BCs/runGCC1402/OutputDir/"
tropomi_cache: "/n/holylfs05/LABS/jacob_lab/imi/ch4/tropomi"