startdate: "20180401T000000"
enddate: "20230331T235959"
imidir: "/n/home06/nbalasus/IMI_BCs/integrated_methane_inversion"
workdir: "/n/holyscratch01/jacob_lab/nbalasus/IMI_BCs"
gccache: "/n/holyscratch01/jacob_lab/nbalasus/IMI_BCs/runGCC1402/OutputDir"
tropomi_cache: "/n/holylfs05/LABS/jacob_lab/imi/ch4/tropomi"
CondaEnv: imi_env

RunGEOSChem: true
WriteBCs: true