#!/bin/bash

#SBATCH -J {RunName}
#SBATCH -c 4
#SBATCH -N 1
#SBATCH -p huce_intel
#SBATCH --mem 2000
#SBATCH -t 0-24:00

x=${SLURM_ARRAY_TASK_ID}

### Add zeros to string name
if [ $x -lt 10 ]; then
   xstr="000${x}"
elif [ $x -lt 100 ]; then
   xstr="00${x}"
elif [ $x -lt 1000 ]; then
   xstr="0${x}"
else
   xstr="${x}"
fi

cd {RunName}_${xstr}
./{RunName}_${xstr}.run

exit 0
