#!/bin/bash

# This script sets up SLURM configuration on AWS. It is necessary because
# instance hardware and IPs change when creating a new instance.
# The script should be run with root permissions and is configured to run
# automatically on system boot in the Integrated Methane Inversion AMI.
cp /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/base_slurm.conf /home/ubuntu/integrated_methane_inversion/new_slurm.conf
/home/ubuntu/miniconda/bin/python /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/configure_slurm.py
cp /home/ubuntu/integrated_methane_inversion/new_slurm.conf /etc/slurm-llnl/slurm.conf
rm /home/ubuntu/integrated_methane_inversion/new_slurm.conf
/usr/sbin/service slurmd restart
/usr/sbin/service slurmctld restart

# Fix issue when switching instance types where node claims to be drained
scontrol update nodename=$HOSTNAME state=idle
