#!/bin/bash

# This script sets up SLURM configuration on AWS. It is necessary because
# instance hardware and IPs change when creating a new instance.
# The script should be run with root permissions and is configured to run
# automatically on system boot in the Integrated Methane Inversion AMI.
# To update crontab job that runs at boot run the following commands:
# (1) $ sudo su root # assume the root user
# (2) $ crontab -l # to list existing crontab commands
# (3) $ crontab -e # create a new crontab file using a default editor
# (4) edit it as you see fit (eg. @reboot /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/initialize_slurm)
# (5) save and overwrite the existing file eg. /var/spool/cron/crontabs/root
# (6) $ exit # to exit root user access

# sleep for a few seconds to give slurmd time to startup
sleep 9

# configure slurm
cp /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/base_slurm.conf /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/new_slurm.conf
python3 /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/configure_slurm.py

# put newly generated slurm.conf in correct locations
cp /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/new_slurm.conf /etc/slurm/slurm.conf
rm /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/new_slurm.conf

# also add a cgroup.conf file
cp /home/ubuntu/integrated_methane_inversion/envs/aws/slurm/cgroup.conf /etc/slurm/cgroup.conf

# start munge and slurm services
service munge restart
service slurmctld restart
service slurmd restart

# Fix issue when switching instance types where node claims to be drained
scontrol update nodename=$HOSTNAME state=idle