name: Deploy to ECR
on:
  push:
    branches: [ dev ]
    tags:
      - '*'

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Check disk usage before build
      run: df -h

    - name: Set IMAGE_TAG
      id: image_tag
      run: |
        if [ "${{ github.event_name }}" == "push" ] && [ -n "${{ github.ref_name }}" ]; then
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Build, tag, and push al2 image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: w1q7j9l2
        REPOSITORY: imi-al2-docker-image
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        docker build -f resources/containers/al2/Dockerfile -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG . --platform=linux/amd64
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker rmi $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker system prune -f

    - name: Check disk usage after 1st build
      run: df -h

    - name: Build, tag, and push ubuntu image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: w1q7j9l2
        REPOSITORY: imi-ubuntu-docker-image
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        docker build -f resources/containers/ubuntu/Dockerfile -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG . --platform=linux/amd64
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker rmi $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker system prune -f

    - name: Check disk usage after build
      run: df -h
